/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { type AdditionalDataHolder, type BackedModel, type BackingStore, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns a User
 */
export function createUserFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUser;
}
/**
 * The deserialization information for the current model
 * @returns a Record<string, (node: ParseNode) => void>
 */
export function deserializeIntoUser(user: Partial<User> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "backingStoreEnabled": n => { user.backingStoreEnabled = true; },
        "email": n => { user.email = n.getStringValue(); },
        "id": n => { user.id = n.getStringValue(); },
        "name": n => { user.name = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeUser(writer: SerializationWriter, user: Partial<User> | undefined = {}) : void {
    writer.writeStringValue("email", user.email);
    writer.writeStringValue("id", user.id);
    writer.writeStringValue("name", user.name);
    writer.writeAdditionalData(user.additionalData);
}
export interface User extends AdditionalDataHolder, BackedModel, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Stores model information.
     */
    backingStoreEnabled?: boolean;
    /**
     * The email property
     */
    email?: string;
    /**
     * The id property
     */
    id?: string;
    /**
     * The name property
     */
    name?: string;
}
/* tslint:enable */
/* eslint-enable */
